services:
    shop_illumination.registration.form.type:
        class: ShopIllumination\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: shop_illumination_user_registration }
    shop_illumination.user_manager.default:
        class: ShopIllumination\UserBundle\Entity\UserManager
        arguments: [@security.encoder_factory, @fos_user.util.username_canonicalizer, @fos_user.util.email_canonicalizer, @fos_user.entity_manager, %fos_user.model.user.class%]